### PR TITLE
Use float_values numpy array for storing the 15 float values in GSCO.

### PR DESCRIPTION
**Pull request by rmjarvis**
An idea floated on todays CI telecon to reduce the memory footprint of the GSCO instances.

### CODE REVIEW

**Comment by danielsf** [comment]
Given that we occasionally end up stuffing new things into the GalSimCelestialObject (for instance, the number of knots in Francois' model), we should probably add a unit test to make sure that the property getters return the same thing that is given to `__init__`.  I can do that.

**Comment by danielsf** [comment]
Oh.  Nevermind. This PR is from a fork.  Do you mind adding such a unit test, @rmjarvis ?

**Comment by rmjarvis** [comment]
I was hoping there would be some Travis run that would check that I didn't break anything with this.  But it seems that the unit tests aren't being run automatically.  

Is there a standard way for me to install this package and run tests (and then to add a new one and run it) that you could point me to?  Or do I need to have the full stack installed and then do some complicated eups esoterica?

**Comment by danielsf** [comment]
It is, unfortunately, the latter.

If you want to just go ahead and merge, I (as a member of the EUPSophonic community) can write the unit test in a different branch.

**Comment by rmjarvis** [comment]
Or if you want, you can make a branch and merge this onto that branch instead of master.  If you don't want to sully master with possibly error-prone code.

**Comment by danielsf** [comment]
Added the unit test in

https://github.com/lsst/sims_GalSimInterface/pull/67

**Pull request closed without merging**
