### PR TITLE
add pointing info to detector FITS headers

### PR DESCRIPTION
**Pull request by jchiang87**
This info will enable the imSim script to generate ingestible `raw` files for `obs_lsstCam` from the eimage files.

### CODE REVIEW

**Comment by cwwalter** [comment]
So, this makes it so that e-images will work with obs_lsstCam too and we don't need obs_lsstSims for it?  

Sorry.. I'm not quite positive what the change does.  Are only those headers are missing and it basically makes it look like one big amp with some initial pointing info? Thanks!

**Comment by jchiang87** [comment]
This is needed to provide the pointing info to the write_amp_image_file.py script that writes the raw files for obs_lsstCam.  Currently, that script (in a branch) needs to retrieve that info from the instance catalog that was used.  This change has no direct relationship to the use of obs_lsstSim.

**Comment by cwwalter** [comment]
Ah got it. OK thanks.

**Comment by danielsf** [comment]
This looks good to me.  Let me run a Jenkins job before hitting "approve".

**Pull request merged**
